export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_PAYMENT_REQUEST = "CREATE_ORDER_PAYMENT_REQUEST";
export const CREATE_ORDER_PAYMENT_SUCCESS = "CREATE_ORDER_PAYMENT_SUCCESS";
export const CREATE_ORDER_PAYMENT_FAIL = "CREATE_ORDER_PAYMENT_FAIL";
export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR"

export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST"
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS"
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL"

export const GET_ONE_ORDER_DETAILS_REQUEST = "GET_ONE_ORDER_DETAILS_REQUEST"
export const GET_ONE_ORDER_DETAILS_SUCCESS = "GET_ONE_ORDER_DETAILS_SUCCESS"
export const GET_ONE_ORDER_DETAILS_FAIL = "GET_ONE_ORDER_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";